
package com.initialjiang.wserice.demo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JdkWS", targetNamespace = "http://demo.wserice.initialjiang.com/")
@XmlSeeAlso({
    com.initialjiang.wserice.demo.ObjectFactory.class,
    demo.ObjectFactory.class
})
public interface JdkWS {


    /**
     * 
     * @param value
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doSomething", targetNamespace = "http://demo.wserice.initialjiang.com/", className = "com.initialjiang.wserice.demo.DoSomething")
    @ResponseWrapper(localName = "doSomethingResponse", targetNamespace = "http://demo.wserice.initialjiang.com/", className = "com.initialjiang.wserice.demo.DoSomethingResponse")
    @Action(input = "http://demo.wserice.initialjiang.com/JdkWS/doSomethingRequest", output = "http://demo.wserice.initialjiang.com/JdkWS/doSomethingResponse")
    public String doSomething(
        @WebParam(name = "value", targetNamespace = "http://demo/")
        String value);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadFile", targetNamespace = "http://demo.wserice.initialjiang.com/", className = "com.initialjiang.wserice.demo.UploadFile")
    @ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://demo.wserice.initialjiang.com/", className = "com.initialjiang.wserice.demo.UploadFileResponse")
    @Action(input = "http://demo.wserice.initialjiang.com/JdkWS/uploadFileRequest", output = "http://demo.wserice.initialjiang.com/JdkWS/uploadFileResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://demo.wserice.initialjiang.com/JdkWS/uploadFile/Fault/IOException")
    })
    public String uploadFile(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1)
        throws IOException_Exception
    ;

}
