
package com.initialjiang.wserice.demo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JdkWSService", targetNamespace = "http://demo.wserice.initialjiang.com/", wsdlLocation = "http://localhost:8080/jdkwsdemo/demo.JdkWebService?wsdl")
public class JdkWSService
    extends Service
{

    private final static URL JDKWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException JDKWSSERVICE_EXCEPTION;
    private final static QName JDKWSSERVICE_QNAME = new QName("http://demo.wserice.initialjiang.com/", "JdkWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/jdkwsdemo/demo.JdkWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JDKWSSERVICE_WSDL_LOCATION = url;
        JDKWSSERVICE_EXCEPTION = e;
    }

    public JdkWSService() {
        super(__getWsdlLocation(), JDKWSSERVICE_QNAME);
    }

    public JdkWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JDKWSSERVICE_QNAME, features);
    }

    public JdkWSService(URL wsdlLocation) {
        super(wsdlLocation, JDKWSSERVICE_QNAME);
    }

    public JdkWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JDKWSSERVICE_QNAME, features);
    }

    public JdkWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JdkWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JdkWS
     */
    @WebEndpoint(name = "JdkWSPort")
    public JdkWS getJdkWSPort() {
        return super.getPort(new QName("http://demo.wserice.initialjiang.com/", "JdkWSPort"), JdkWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JdkWS
     */
    @WebEndpoint(name = "JdkWSPort")
    public JdkWS getJdkWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://demo.wserice.initialjiang.com/", "JdkWSPort"), JdkWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JDKWSSERVICE_EXCEPTION!= null) {
            throw JDKWSSERVICE_EXCEPTION;
        }
        return JDKWSSERVICE_WSDL_LOCATION;
    }

}
